#!/usr/bin/env python3
from pathlib import Path

from asgion.rules import ALL_RULES

_ASGI_MAIN = "https://asgi.readthedocs.io/en/latest/specs/main.html"
_ASGI_HTTP = "https://asgi.readthedocs.io/en/latest/specs/www.html"
_ASGI_WS = "https://asgi.readthedocs.io/en/latest/specs/websocket.html"
_ASGI_LIFESPAN = "https://asgi.readthedocs.io/en/latest/specs/lifespan.html"

LAYER_TITLES = {
    "general": "General ASGI (Layer 0)",
    "http.events": "HTTP Events (Layer 4)",
    "http.fsm": "HTTP State Machine (Layer 7)",
    "ws.events": "WebSocket Events (Layer 5)",
    "ws.fsm": "WebSocket State Machine (Layer 8)",
    "lifespan.events": "Lifespan Events (Layer 6)",
    "lifespan.fsm": "Lifespan State Machine (Layer 9)",
}

LAYER_SPEC_REFS: dict[str, str] = {
    "general": _ASGI_MAIN,
    "http.events": _ASGI_HTTP,
    "http.fsm": _ASGI_HTTP,
    "ws.events": _ASGI_WS,
    "ws.fsm": _ASGI_WS,
    "lifespan.events": _ASGI_LIFESPAN,
    "lifespan.fsm": _ASGI_LIFESPAN,
}

LAYER_ORDER = [
    "general",
    "http.events",
    "http.fsm",
    "ws.events",
    "ws.fsm",
    "lifespan.events",
    "lifespan.fsm",
]


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def generate() -> str:
    layers: dict[str, list[object]] = {}
    for r in ALL_RULES:
        key = r.layer or "general"
        layers.setdefault(key, []).append(r)

    lines: list[str] = []
    w = lines.append

    w("<!-- Auto-generated by docs/generate_rules.py - do not edit manually -->")
    w("")
    w("# Asgion Rules Reference")
    w("")
    w("All validation rules that Asgion checks, grouped by protocol layer.")
    w("")
    w(
        "Rules are based on the "
        "[ASGI spec](https://asgi.readthedocs.io/en/latest/) "
        "([asgiref](https://github.com/django/asgiref))."
    )
    w("")
    w(f"**Total: {len(ALL_RULES)} rules**")
    w("")
    w("| Severity | Meaning |")
    w("|----------|---------|")
    w("| `error` | ASGI spec violation - something is broken |")
    w("| `warning` | Potential problem - likely a bug |")
    w("| `info` | Recommendation - could be improved |")
    w("| `perf` | Performance concern |")
    w("")
    w("> To suppress specific rules:")
    w("> ```python")
    w('> inspect(app, exclude_rules={"HE-012", "G-008"})')
    w("> ```")
    w("")
    w("---")
    w("")

    for layer_key in LAYER_ORDER:
        rules = layers.get(layer_key, [])
        if not rules:
            continue
        title = LAYER_TITLES.get(layer_key, layer_key)
        w(f"## {title}")
        spec_url = LAYER_SPEC_REFS.get(layer_key)
        if spec_url:
            w(f"> Spec: <{spec_url}>")
        w("")
        w("| ID | Severity | Summary | Hint |")
        w("|----|----------|---------|------|")
        for r in rules:
            hint = _escape(r.hint) if r.hint else "-"
            summary = _escape(r.summary)
            w(f"| `{r.id}` | {r.severity} | {summary} | {hint} |")
        w("")

    return "\n".join(lines)


def main() -> None:
    out = Path(__file__).parent / "rules.md"
    content = generate()
    out.write_text(content)


if __name__ == "__main__":
    main()
